baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'tty-share'
description: 'Simple fast and secure terminal sharing for Linux and Macos.'
tagline: 'Terminal sharing for Linux and Macos'
url: tty-share.com

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-143397005-1

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
